export const users = [
  { id: '1', name: 'John Smith', email: 'john.teacher@example.com', role: 'teacher', avatar: 'https://i.pravatar.cc/150?img=1' },
  { id: '2', name: 'Alice Johnson', email: 'alice.admin@example.com', role: 'admin', avatar: 'https://i.pravatar.cc/150?img=2' },
  { id: '3', name: 'Bob Williams', email: 'bob.owner@example.com', role: 'owner', avatar: 'https://i.pravatar.cc/150?img=3' },
];

export const students = [
  { id: '1', name: 'John Smith', phone: '+1234567890' },
  { id: '2', name: 'Sarah Johnson', phone: '+1987654321' },
  { id: '3', name: 'Michael Brown', phone: '+1122334455' },
  { id: '4', name: 'Emily Davis', phone: '+1567890123' },
  { id: '5', name: 'David Miller', phone: '+1321654987' },
  { id: '6', name: 'Jessica Wilson', phone: '+1765432198' }
];

export const sessions = [
  {
    id: '1',
    date: '2024-08-15',
    startTime: '09:00',
    endTime: '10:00',
    teacherId: '1',
    teacherName: 'John Smith',
    studentId: '1',
    studentName: 'Alice Brown',
    status: 'scheduled',
    attendanceConfirmed: true,
    paymentStatus: 'paid',
  },
  {
    id: '2',
    date: '2024-08-16',
    startTime: '14:00',
    endTime: '15:00',
    teacherId: '2',
    teacherName: 'Jane Doe',
    studentId: '2',
    studentName: 'Bob Johnson',
    status: 'completed',
    attendanceConfirmed: true,
    paymentStatus: 'paid',
  },
  {
    id: '3',
    date: '2024-08-17',
    startTime: '11:00',
    endTime: '12:00',
    teacherId: '1',
    teacherName: 'John Smith',
    studentId: '3',
    studentName: 'Charlie Green',
    status: 'cancelled-by-teacher',
    attendanceConfirmed: false,
    paymentStatus: 'pending',
  },
  {
    id: '4',
    date: '2024-08-18',
    startTime: '16:00',
    endTime: '17:00',
    teacherId: '3',
    teacherName: 'David Lee',
    studentId: '4',
    studentName: 'Diana White',
    status: 'scheduled',
    attendanceConfirmed: false,
    paymentStatus: 'partially-paid',
  },
  {
    id: '5',
    date: '2024-08-19',
    startTime: '10:00',
    endTime: '11:00',
    teacherId: '2',
    teacherName: 'Jane Doe',
    studentId: '5',
    studentName: 'Eve Black',
    status: 'completed',
    attendanceConfirmed: true,
    paymentStatus: 'paid',
  },
  {
    id: '6',
    date: '2024-08-20',
    startTime: '13:00',
    endTime: '14:00',
    teacherId: '1',
    teacherName: 'John Smith',
    studentId: '6',
    studentName: 'Frank Grey',
    status: 'scheduled',
    attendanceConfirmed: false,
    paymentStatus: 'pending',
  },
];

export const payments = [
  {
    id: '1',
    sessionId: '1',
    date: '2024-08-15',
    amount: 50.00,
    method: 'cash',
    adminFee: 5.00,
    teacherFee: 45.00,
  },
  {
    id: '2',
    sessionId: '2',
    date: '2024-08-16',
    amount: 60.00,
    method: 'bank-transfer',
    adminFee: 6.00,
    teacherFee: 54.00,
  },
  {
    id: '3',
    sessionId: '4',
    date: '2024-08-18',
    amount: 40.00,
    method: 'gcash',
    adminFee: 4.00,
    teacherFee: 36.00,
  },
];
